### ISSUE TITLE
Installation failure due to the missing file nan_persistent_12_inl.h

### ISSUE THREAD

**Issue by zedtux** [juliogarciag/atom-rails-model-schema#24]
Installing the package in Atom running on my Debian Jessie, I got the following output:

```
> runas@3.1.1 install /tmp/apm-install-dir-116727-6501-1yu063v/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-116727-6501-1yu063v/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-116727-6501-1yu063v/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas/build'

In file included from ../../nan/nan.h:196:0,
                 from ../src/main.cc:1:
../../nan/nan_new.h:9:0: error: unterminated #ifndef
 #ifndef NAN_NEW_H_
 ^
In file included from ../src/main.cc:1:0:
../../nan/nan.h:311:62: fatal error: nan_persistent_12_inl.h: No such file or directory
 # include "nan_persistent_12_inl.h"  // NOLINT(build/include)
                                                              ^
compilation terminated.
The bug is not reproducible, so it is likely a hardware or OS problem.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-116727-6501-1yu063v/node_modules/rails-model-schema/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/zedtux/.atom/.apm/.apmrc" "--userconfig" "/home/zedtux/.atom/.apmrc" "install" "/tmp/d-116727-6501-1ws6p2g/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116727-6501-1yu063v/npm-debug.log
```

The issue seems to be the missing package [nan](https://github.com/nodejs/nan) which has the missing file.

**Comment by zedtux** [comment]
Looking closer to the error it seems that the error relates to the `pathwatcher` package

**Comment by zedtux** [comment]
I don't have this issue anymore so I close this issue.
